alias gff='git diff'
alias gpl='git pull'
alias gt='git status'
alias gtc='git add . && git commit -m'
alias gtp='git push'
alias nb='npm run build'
alias nd='npm run build:dev'
alias nt='npm run test'
